from pathlib import Path
import traceback
import os

import uvicorn

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel

from starlette.middleware.sessions import SessionMiddleware

from dotenv import load_dotenv

from google.oauth2 import id_token
from google.auth.transport import requests as google_requests
from backend import run_travel_agent


# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

# Load variables from .env
load_dotenv()

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
SESSION_SECRET = os.getenv("SESSION_SECRET")


# Check required environment variables
if not GOOGLE_CLIENT_ID:
    print("WARNING: GOOGLE_CLIENT_ID is not set in .env")

if not SESSION_SECRET:
    print("WARNING: SESSION_SECRET is not set in .env")


# ============================================================
# FASTAPI APPLICATION
# ============================================================

app = FastAPI(
    title="WANDERWISE AI ",
    description="LangGraph Multi-Agent Travel Planner with FastAPI Frontend",
    version="1.0.0"
)


# ============================================================
# SESSION MIDDLEWARE
# ============================================================

app.add_middleware(
    SessionMiddleware,
    secret_key=SESSION_SECRET or "temporary-development-secret",
    same_site="lax",
    https_only=False,
    max_age=60 * 60 * 24 * 7  # 7 days
)


# ============================================================
# STATIC FILES
# ============================================================

app.mount(
    "/static",
    StaticFiles(directory=str(BASE_DIR / "static")),
    name="static"
)


# ============================================================
# TEMPLATES
# ============================================================

templates = Jinja2Templates(
    directory=str(BASE_DIR / "templates")
)


# ============================================================
# REQUEST MODELS
# ============================================================

class TravelRequest(BaseModel):
    message: str
    thread_id: str | None = None


# ============================================================
# AUTHENTICATION HELPER
# ============================================================

def get_current_user(request: Request):
    """
    Get the currently logged-in Google user from the session.

    Returns:
        dict: User information if logged in
        None: If user is not logged in
    """

    return request.session.get("user")


# ============================================================
# LOGIN PAGE
# ============================================================

@app.get("/login", response_class=HTMLResponse)
async def login_page(request: Request):

    # If already logged in, go directly to TripMate
    if get_current_user(request):
        return RedirectResponse(
            url="/",
            status_code=302
        )

    return templates.TemplateResponse(
        request=request,
        name="login.html",
        context={
            "google_client_id": GOOGLE_CLIENT_ID
        }
    )


# ============================================================
# GOOGLE AUTHENTICATION
# ============================================================

@app.post("/auth/google")
async def google_login(request: Request):

    """
    Receives the Google credential generated by Google Identity
    Services and verifies the ID token.

    If valid:
        - Creates a session
        - Stores basic Google user information
        - Redirects to TripMate

    If invalid:
        - Returns HTTP 401
    """

    try:

        # ----------------------------------------------------
        # Get form data sent by Google
        # ----------------------------------------------------

        form = await request.form()

        credential = form.get("credential")

        if not credential:

            return JSONResponse(
                status_code=400,
                content={
                    "success": False,
                    "error": "Google credential was not provided."
                }
            )


        # ----------------------------------------------------
        # Verify Google ID Token
        # ----------------------------------------------------

        user_info = id_token.verify_oauth2_token(
            credential,
            google_requests.Request(),
            GOOGLE_CLIENT_ID
        )


        # ----------------------------------------------------
        # Extract user information
        # ----------------------------------------------------

        google_user = {
            "google_id": user_info.get("sub"),
            "email": user_info.get("email"),
            "name": user_info.get("name"),
            "picture": user_info.get("picture"),
            "email_verified": user_info.get("email_verified", False)
        }


        # ----------------------------------------------------
        # Check email verification
        # ----------------------------------------------------

        if not google_user["email_verified"]:

            return JSONResponse(
                status_code=403,
                content={
                    "success": False,
                    "error": "Your Google email is not verified."
                }
            )


        # ----------------------------------------------------
        # Store user in session
        # ----------------------------------------------------

        request.session["user"] = google_user


        print(
            f"Google login successful: "
            f"{google_user.get('email')}"
        )


        # ----------------------------------------------------
        # Redirect to TripMate
        # ----------------------------------------------------

        return RedirectResponse(
            url="/",
            status_code=303
        )


    except ValueError as e:

        # Invalid Google token
        print("Google token verification failed:", e)

        return JSONResponse(
            status_code=401,
            content={
                "success": False,
                "error": "Invalid or expired Google authentication token."
            }
        )


    except Exception as e:

        print("Google authentication error:", e)
        traceback.print_exc()

        return JSONResponse(
            status_code=500,
            content={
                "success": False,
                "error": "Google authentication failed."
            }
        )


# ============================================================
# LOGOUT
# ============================================================

@app.get("/logout")
async def logout(request: Request):

    # Remove all session data
    request.session.clear()

    return RedirectResponse(
        url="/login",
        status_code=302
    )


# ============================================================
# HOME PAGE
# ============================================================

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):

    # --------------------------------------------------------
    # Check authentication
    # --------------------------------------------------------

    user = get_current_user(request)

    if not user:

        return RedirectResponse(
            url="/login",
            status_code=302
        )


    # --------------------------------------------------------
    # Render TripMate
    # --------------------------------------------------------

    return templates.TemplateResponse(
        request=request,
        name="index.html",
        context={
            "user": user
        }
    )


# ============================================================
# TRAVEL API
# ============================================================

@app.post("/api/travel")
async def travel_planner(
    request: Request,
    request_data: TravelRequest
):

    user = get_current_user(request)

    if not user:
        return JSONResponse(
            status_code=401,
            content={
                "success": False,
                "error": "You must be logged in to use TripMate AI."
            }
        )

    try:
        # Import backend ONLY when travel planning is actually requested
        from backend import run_travel_agent

        user_message = request_data.message.strip()

        if not user_message:
            return JSONResponse(
                status_code=400,
                content={
                    "success": False,
                    "error": "Message cannot be empty."
                }
            )

        result = run_travel_agent(
            user_input=user_message,
            thread_id=request_data.thread_id
        )

        return JSONResponse(
            content={
                "success": True,
                "thread_id": result["thread_id"],
                "answer": result["answer"],
                "flight_results": result["flight_results"],
                "hotel_results": result["hotel_results"],
                "weather_results": result["weather_results"],
                "local_info_results": result["local_info_results"],
                "itinerary": result["itinerary"],
                "price_prediction": result["price_prediction"],
                "sentiment_summary": result["sentiment_summary"],
                "recommended_attractions": result["recommended_attractions"],
                "llm_calls": result["llm_calls"],
            }
        )

    except Exception as e:
        print("ERROR:", e)
        traceback.print_exc()

        return JSONResponse(
            status_code=500,
            content={
                "success": False,
                "error": str(e)
            }
        )

# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/health")
async def health_check():

    return {
        "status": "ok",
        "message": "AI Travel Planner API is running"
    }


# ============================================================
# ANALYTICS DASHBOARD
# ============================================================

@app.get("/api/analytics/dashboard-summary")
async def dashboard_summary(request: Request):

    # --------------------------------------------------------
    # Authentication check
    # --------------------------------------------------------

    user = get_current_user(request)

    if not user:

        return JSONResponse(
            status_code=401,
            content={
                "success": False,
                "error": "Authentication required."
            }
        )


    try:

        from sqlalchemy import func

        from db.database import (
            SessionLocal,
            Base,
            engine
        )

        from db.models import TravelPlanRecord


        # ----------------------------------------------------
        # Make sure tables exist
        # ----------------------------------------------------

        Base.metadata.create_all(
            bind=engine
        )


        db = SessionLocal()


        try:

            # ------------------------------------------------
            # Total plans
            # ------------------------------------------------

            total_plans = (
                db.query(
                    func.count(TravelPlanRecord.id)
                ).scalar()
                or 0
            )


            # ------------------------------------------------
            # Sentiment scores
            # ------------------------------------------------

            rows = (
                db.query(
                    TravelPlanRecord.sentiment_summary
                )
                .filter(
                    TravelPlanRecord.sentiment_summary.isnot(None)
                )
                .all()
            )


            scores = [

                r[0]["average_score"]

                for r in rows

                if r[0]
                and r[0].get("average_score") is not None

            ]


            # ------------------------------------------------
            # Average sentiment
            # ------------------------------------------------

            avg_sentiment = (

                round(
                    sum(scores) / len(scores),
                    3
                )

                if scores

                else None

            )


            return {

                "total_plans_generated": total_plans,

                "average_review_sentiment": avg_sentiment,

            }


        finally:

            db.close()


    except Exception as e:

        return JSONResponse(
            status_code=502,
            content={
                "error":
                    f"Could not load dashboard summary: {e}"
            },
        )


# ============================================================
# FAVICON
# ============================================================

@app.get("/favicon.ico")
async def favicon():

    return JSONResponse(
        content={}
    )


# ============================================================
# RUN APPLICATION
# ============================================================

if __name__ == "__main__":

    uvicorn.run(
        "app:app",
        host="127.0.0.1",
        port=8000,
        reload=True
    )